"""
Entity API - Create Entity

Demonstrates creating a new entity record.

To create a record:
1. Get the template from /new endpoint
2. Fill in required fields
3. POST without key fields (absence of key = insert)

Usage:
    python scripts/entity/03_create_entity.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import httpx
from common.auth import get_token, get_auth_headers
from common.config import load_config

import warnings
warnings.filterwarnings("ignore")


def get_new_template(base_url: str, endpoint: str, headers: dict, verify_ssl: bool) -> dict:
    """Get a new template for creating a record."""
    response = httpx.get(
        f"{base_url}{endpoint}/new",
        headers=headers,
        verify=verify_ssl,
        follow_redirects=True,
        timeout=30.0
    )
    response.raise_for_status()
    return response.json()


def create_entity(base_url: str, endpoint: str, data: dict,
                   headers: dict, verify_ssl: bool) -> dict:
    """Create a new entity record."""
    response = httpx.post(
        f"{base_url}{endpoint}",
        headers={**headers, "Content-Type": "application/json"},
        json=data,
        verify=verify_ssl,
        follow_redirects=True,
        timeout=30.0
    )
    response.raise_for_status()
    return response.json()


def main():
    print("Entity API - Create Entity")
    print("=" * 60)

    config = load_config()
    token_data = get_token(config)
    headers = get_auth_headers(token_data["AccessToken"])

    print(f"Server: {config.base_url}")

    # Example 1: Get a template
    print("\n1. Getting new customer template:")
    print("-" * 50)

    try:
        template = get_new_template(
            config.base_url,
            "/api/sales/customers",
            headers,
            config.verify_ssl
        )

        print(f"  Template has {len(template)} fields")
        print("\n  Key required fields:")

        # Show some important fields
        important = ["CustomerCode", "CustomerName", "Address1", "City", "State", "Zip"]
        for field in important:
            value = template.get(field)
            print(f"    {field}: {value if value else '(empty)'}")

    except httpx.HTTPStatusError as e:
        print(f"  Error: {e.response.status_code}")
        print(f"  {e.response.text[:200]}")
        return
    except Exception as e:
        print(f"  Error: {e}")
        return

    # Example 2: Show create workflow (without actually creating)
    print("\n2. Create workflow (demonstration only):")
    print("-" * 50)

    print("  To create a customer, you would:")
    print("  1. Get template: GET /api/sales/customers/new")
    print("  2. Fill required fields:")
    print("     template['CustomerName'] = 'New Customer Inc'")
    print("     template['Address1'] = '123 Main Street'")
    print("     template['City'] = 'Cedar Rapids'")
    print("     template['State'] = 'IA'")
    print("  3. Remove/leave empty the key field (CustomerCode)")
    print("  4. POST to: /api/sales/customers")
    print()
    print("  The absence of CustomerCode tells API to INSERT, not UPDATE")

    # Example 3: Show the payload structure
    print("\n3. Sample create payload:")
    print("-" * 50)

    sample_payload = {
        "CustomerName": "New Customer Inc",
        "Address1": "123 Main Street",
        "City": "Cedar Rapids",
        "State": "IA",
        "Zip": "52402",
        "Country": "USA"
    }

    print("  {")
    for key, value in sample_payload.items():
        print(f'    "{key}": "{value}",')
    print("  }")

    print("\n  Note: CustomerCode is NOT included = new record")
    print("        If CustomerCode IS included = update existing")

    # Example 4: Show response structure
    print("\n4. Expected response:")
    print("-" * 50)
    print("  On success, the API returns the created record with")
    print("  the generated CustomerCode filled in.")
    print()
    print("  {")
    print('    "CustomerCode": 999999,  // Generated by P21')
    print('    "CustomerName": "New Customer Inc",')
    print('    "Address1": "123 Main Street",')
    print("    ...")
    print("  }")

    print("\n" + "=" * 60)
    print("Create entity examples complete!")
    print("\nKey points:")
    print("- GET /new to get a template with default values")
    print("- Omit key field (e.g., CustomerCode) for INSERT")
    print("- Include key field for UPDATE")
    print("- Only include fields you want to set")


if __name__ == "__main__":
    main()
